//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Lib.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string AccentColorSource_Custom {
            get {
                return ResourceManager.GetString("AccentColorSource_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string AccentColorSource_System {
            get {
                return ResourceManager.GetString("AccentColorSource_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string AlwaysOnUSBState_Off {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, always.
        /// </summary>
        public static string AlwaysOnUSBState_OnAlways {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On, when sleeping.
        /// </summary>
        public static string AlwaysOnUSBState_OnWhenSleeping {
            get {
                return ResourceManager.GetString("AlwaysOnUSBState_OnWhenSleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile will not apply without AC adapter (Full wattage) connected..
        /// </summary>
        public static string AmdOverclocking_Ac_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Ac_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not initialized..
        /// </summary>
        public static string AmdOverclocking_Not_Initialized_Message {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Initialized_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported..
        /// </summary>
        public static string AmdOverclocking_Not_Supported {
            get {
                return ResourceManager.GetString("AmdOverclocking_Not_Supported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: For safety, these steps will be skipped on startup: {0}. All other steps will execute normally..
        /// </summary>
        public static string Automation_Warning_Startup {
            get {
                return ResourceManager.GetString("Automation_Warning_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string AutorunState_Disabled {
            get {
                return ResourceManager.GetString("AutorunState_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string AutorunState_Enabled {
            get {
                return ResourceManager.GetString("AutorunState_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled (delayed).
        /// </summary>
        public static string AutorunState_EnabledDelayed {
            get {
                return ResourceManager.GetString("AutorunState_EnabledDelayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balanced.
        /// </summary>
        public static string Balanced {
            get {
                return ResourceManager.GetString("Balanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string BatteryNightChargeState_Off {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string BatteryNightChargeState_On {
            get {
                return ResourceManager.GetString("BatteryNightChargeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conservation.
        /// </summary>
        public static string BatteryState_Conservation {
            get {
                return ResourceManager.GetString("BatteryState_Conservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string BatteryState_Normal {
            get {
                return ResourceManager.GetString("BatteryState_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Charge.
        /// </summary>
        public static string BatteryState_RapidCharge {
            get {
                return ResourceManager.GetString("BatteryState_RapidCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Performance.
        /// </summary>
        public static string BestPerformance {
            get {
                return ResourceManager.GetString("BestPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Power Efficiency.
        /// </summary>
        public static string BestPowerEfficiency {
            get {
                return ResourceManager.GetString("BestPowerEfficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Fan.
        /// </summary>
        public static string CustomFanCurveControl_Fan_CPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPU Fan.
        /// </summary>
        public static string CustomFanCurveControl_Fan_GPU {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_GPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Fan.
        /// </summary>
        public static string CustomFanCurveControl_Fan_System {
            get {
                return ResourceManager.GetString("CustomFanCurveControl_Fan_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string CustomSpecialKey_Custom {
            get {
                return ResourceManager.GetString("CustomSpecialKey_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string CustomSpecialKey_Default {
            get {
                return ResourceManager.GetString("CustomSpecialKey_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FlipToStartState_Off {
            get {
                return ResourceManager.GetString("FlipToStartState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FlipToStartState_On {
            get {
                return ResourceManager.GetString("FlipToStartState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FnLockState_Off {
            get {
                return ResourceManager.GetString("FnLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FnLockState_On {
            get {
                return ResourceManager.GetString("FnLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered Off.
        /// </summary>
        public static string GPUController_PoweredOff {
            get {
                return ResourceManager.GetString("GPUController_PoweredOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered On.
        /// </summary>
        public static string GPUController_PoweredOn {
            get {
                return ResourceManager.GetString("GPUController_PoweredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string HardwareSensorsState_Off {
            get {
                return ResourceManager.GetString("HardwareSensorsState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string HardwareSensorsState_On {
            get {
                return ResourceManager.GetString("HardwareSensorsState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string HDRState_Off {
            get {
                return ResourceManager.GetString("HDRState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string HDRState_On {
            get {
                return ResourceManager.GetString("HDRState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dGPU.
        /// </summary>
        public static string HybridModeState_Off {
            get {
                return ResourceManager.GetString("HybridModeState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string HybridModeState_On {
            get {
                return ResourceManager.GetString("HybridModeState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid-Auto.
        /// </summary>
        public static string HybridModeState_OnAuto {
            get {
                return ResourceManager.GetString("HybridModeState_OnAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid-iGPU.
        /// </summary>
        public static string HybridModeState_OnIGPUOnly {
            get {
                return ResourceManager.GetString("HybridModeState_OnIGPUOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UMA.
        /// </summary>
        public static string HybridModeState_UMA {
            get {
                return ResourceManager.GetString("HybridModeState_UMA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC Adapter.
        /// </summary>
        public static string InstantBootState_AcAdapter {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC and USB PD.
        /// </summary>
        public static string InstantBootState_AcAdapterAndUsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_AcAdapterAndUsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string InstantBootState_Off {
            get {
                return ResourceManager.GetString("InstantBootState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Power Delivery.
        /// </summary>
        public static string InstantBootState_UsbPowerDelivery {
            get {
                return ResourceManager.GetString("InstantBootState_UsbPowerDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Saving.
        /// </summary>
        public static string ITSMode_Intelligent_Battery_Saving {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Battery_Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intelligent Cooling.
        /// </summary>
        public static string ITSMode_Intelligent_Cooling {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Cooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme Performance.
        /// </summary>
        public static string ITSMode_Intelligent_Extreme_Performance {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Extreme_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geek.
        /// </summary>
        public static string ITSMode_Intelligent_Geek {
            get {
                return ResourceManager.GetString("ITSMode_Intelligent_Geek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string MicrophoneState_Off {
            get {
                return ResourceManager.GetString("MicrophoneState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string MicrophoneState_On {
            get {
                return ResourceManager.GetString("MicrophoneState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alt.
        /// </summary>
        public static string ModifierKey_Alt {
            get {
                return ResourceManager.GetString("ModifierKey_Alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl.
        /// </summary>
        public static string ModifierKey_Ctrl {
            get {
                return ResourceManager.GetString("ModifierKey_Ctrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string ModifierKey_Shift {
            get {
                return ResourceManager.GetString("ModifierKey_Shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string NotificationDuration_Long {
            get {
                return ResourceManager.GetString("NotificationDuration_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string NotificationDuration_Normal {
            get {
                return ResourceManager.GetString("NotificationDuration_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short.
        /// </summary>
        public static string NotificationDuration_Short {
            get {
                return ResourceManager.GetString("NotificationDuration_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom center.
        /// </summary>
        public static string NotificationPosition_BottomCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom left.
        /// </summary>
        public static string NotificationPosition_BottomLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom right.
        /// </summary>
        public static string NotificationPosition_BottomRight {
            get {
                return ResourceManager.GetString("NotificationPosition_BottomRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string NotificationPosition_Center {
            get {
                return ResourceManager.GetString("NotificationPosition_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center left.
        /// </summary>
        public static string NotificationPosition_CenterLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center right.
        /// </summary>
        public static string NotificationPosition_CenterRight {
            get {
                return ResourceManager.GetString("NotificationPosition_CenterRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top center.
        /// </summary>
        public static string NotificationPosition_TopCenter {
            get {
                return ResourceManager.GetString("NotificationPosition_TopCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top left.
        /// </summary>
        public static string NotificationPosition_TopLeft {
            get {
                return ResourceManager.GetString("NotificationPosition_TopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top right.
        /// </summary>
        public static string NotificationPosition_TopRight {
            get {
                return ResourceManager.GetString("NotificationPosition_TopRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OneLevelWhiteKeyboardBacklightState_On {
            get {
                return ResourceManager.GetString("OneLevelWhiteKeyboardBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk 1 Temperature.
        /// </summary>
        public static string OsdItem_Disk1Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk1Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk 2 Temperature.
        /// </summary>
        public static string OsdItem_Disk2Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Disk2Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Core Clock.
        /// </summary>
        public static string OsdItem_E_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_E_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fan.
        /// </summary>
        public static string OsdItem_Fan {
            get {
                return ResourceManager.GetString("OsdItem_Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS.
        /// </summary>
        public static string OsdItem_Fps {
            get {
                return ResourceManager.GetString("OsdItem_Fps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame Time.
        /// </summary>
        public static string OsdItem_FrameTime {
            get {
                return ResourceManager.GetString("OsdItem_FrameTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string OsdItem_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1% Low.
        /// </summary>
        public static string OsdItem_LowFps {
            get {
                return ResourceManager.GetString("OsdItem_LowFps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Temperature.
        /// </summary>
        public static string OsdItem_MemoryTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MemoryTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motherboard Temperature.
        /// </summary>
        public static string OsdItem_MotherboardTemperature {
            get {
                return ResourceManager.GetString("OsdItem_MotherboardTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P-Core Clock.
        /// </summary>
        public static string OsdItem_P_Core_Frequency {
            get {
                return ResourceManager.GetString("OsdItem_P_Core_Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string OsdItem_Power {
            get {
                return ResourceManager.GetString("OsdItem_Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string OsdItem_Temperature {
            get {
                return ResourceManager.GetString("OsdItem_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilization.
        /// </summary>
        public static string OsdItem_Utilization {
            get {
                return ResourceManager.GetString("OsdItem_Utilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Temperature.
        /// </summary>
        public static string OsdItem_VramTemperature {
            get {
                return ResourceManager.GetString("OsdItem_VramTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VRAM Utilization.
        /// </summary>
        public static string OsdItem_VramUtilization {
            get {
                return ResourceManager.GetString("OsdItem_VramUtilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string OverdriveState_Off {
            get {
                return ResourceManager.GetString("OverdriveState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string OverdriveState_On {
            get {
                return ResourceManager.GetString("OverdriveState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PanelLogoBacklightState_Off {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PanelLogoBacklightState_On {
            get {
                return ResourceManager.GetString("PanelLogoBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string PortsBacklightState_Off {
            get {
                return ResourceManager.GetString("PortsBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string PortsBacklightState_On {
            get {
                return ResourceManager.GetString("PortsBacklightState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string PowerModeMappingMode_Disabled {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Power Mode.
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerMode {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Power Plan.
        /// </summary>
        public static string PowerModeMappingMode_WindowsPowerPlan {
            get {
                return ResourceManager.GetString("PowerModeMappingMode_WindowsPowerPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        public static string PowerModeState_Balance {
            get {
                return ResourceManager.GetString("PowerModeState_Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme.
        /// </summary>
        public static string PowerModeState_Extreme {
            get {
                return ResourceManager.GetString("PowerModeState_Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string PowerModeState_GodMode {
            get {
                return ResourceManager.GetString("PowerModeState_GodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string PowerModeState_Performance {
            get {
                return ResourceManager.GetString("PowerModeState_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiet.
        /// </summary>
        public static string PowerModeState_Quiet {
            get {
                return ResourceManager.GetString("PowerModeState_Quiet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string RGBKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breath.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Breath {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Breath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Smooth {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_Static {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_Static", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Left.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveLTR {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveLTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wave Right.
        /// </summary>
        public static string RGBKeyboardBacklightEffect_WaveRTL {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightEffect_WaveRTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 4.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Four {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Four", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Off {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 1.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_One {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 3.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Three {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Three", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset 2.
        /// </summary>
        public static string RGBKeyboardBacklightPreset_Two {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightPreset_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fast {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Fastest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Fastest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slow {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slowest.
        /// </summary>
        public static string RGBKeyboardBacklightSpeed_Slowest {
            get {
                return ResourceManager.GetString("RGBKeyboardBacklightSpeed_Slowest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared / Dynamic.
        /// </summary>
        public static string SharedMemory {
            get {
                return ResourceManager.GetString("SharedMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string SpeakerState_Mute {
            get {
                return ResourceManager.GetString("SpeakerState_Mute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute.
        /// </summary>
        public static string SpeakerState_Unmute {
            get {
                return ResourceManager.GetString("SpeakerState_Unmute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_High {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Low {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Medium {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SpectrumKeyboardBacklightBrightness_Off {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightBrightness_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom to Top.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_BottomToTop {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_BottomToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clockwise.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_Clockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_Clockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Clockwise.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_CounterClockwise {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_CounterClockwise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left to Right.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_LeftToRight {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_LeftToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right to Left.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_RightToLeft {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_RightToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top to Bottom.
        /// </summary>
        public static string SpectrumKeyboardBacklightDirection_TopToBottom {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightDirection_TopToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Always {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Bounce.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioBounce {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioBounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Ripple.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AudioRipple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AudioRipple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aurora Sync.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_AuroraSync {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_AuroraSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Change.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorChange {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Pulse.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorPulse {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Wave.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_ColorWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_ColorWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rain.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Rain {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Rain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Screw.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowScrew {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowScrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow Wave.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_RainbowWave {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_RainbowWave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ripple.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Ripple {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Ripple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Smooth {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SpectrumKeyboardBacklightEffectType_Type {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightEffectType_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slow.
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed1 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed2 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        public static string SpectrumKeyboardBacklightSpeed_Speed3 {
            get {
                return ResourceManager.GetString("SpectrumKeyboardBacklightSpeed_Speed3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Theme_System {
            get {
                return ResourceManager.GetString("Theme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string ToggleState_Off {
            get {
                return ResourceManager.GetString("ToggleState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string ToggleState_On {
            get {
                return ResourceManager.GetString("ToggleState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string ToggleState_Toggle {
            get {
                return ResourceManager.GetString("ToggleState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string TouchpadLockState_Off {
            get {
                return ResourceManager.GetString("TouchpadLockState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string TouchpadLockState_On {
            get {
                return ResourceManager.GetString("TouchpadLockState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string UpdateChannel_Beta {
            get {
                return ResourceManager.GetString("UpdateChannel_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dev.
        /// </summary>
        public static string UpdateChannel_Dev {
            get {
                return ResourceManager.GetString("UpdateChannel_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stable.
        /// </summary>
        public static string UpdateChannel_Stable {
            get {
                return ResourceManager.GetString("UpdateChannel_Stable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string UpdateChannel_Test {
            get {
                return ResourceManager.GetString("UpdateChannel_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The downloaded update is not signed by the trusted server certificate {0}.
        /// </summary>
        public static string UpdateChecker_Security_Invalid {
            get {
                return ResourceManager.GetString("UpdateChecker_Security_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid signature thumbprint {0}.
        /// </summary>
        public static string UpdateChecker_Security_Thumbprint {
            get {
                return ResourceManager.GetString("UpdateChecker_Security_Thumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string UpdateCheckFrequency_Never {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string UpdateCheckFrequency_PerDay {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every hour.
        /// </summary>
        public static string UpdateCheckFrequency_PerHour {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        public static string UpdateCheckFrequency_PerMonth {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 3 hours.
        /// </summary>
        public static string UpdateCheckFrequency_PerThreeHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerThreeHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 12 hours.
        /// </summary>
        public static string UpdateCheckFrequency_PerTwelveHours {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerTwelveHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string UpdateCheckFrequency_PerWeek {
            get {
                return ResourceManager.GetString("UpdateCheckFrequency_PerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub.
        /// </summary>
        public static string UpdateMethod_GitHub {
            get {
                return ResourceManager.GetString("UpdateMethod_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        public static string UpdateMethod_Server {
            get {
                return ResourceManager.GetString("UpdateMethod_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string WhiteKeyboardBacklightState_High {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string WhiteKeyboardBacklightState_Low {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string WhiteKeyboardBacklightState_Off {
            get {
                return ResourceManager.GetString("WhiteKeyboardBacklightState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acrylic.
        /// </summary>
        public static string WindowBackdropType_Acrylic {
            get {
                return ResourceManager.GetString("WindowBackdropType_Acrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mica.
        /// </summary>
        public static string WindowBackdropType_Mica {
            get {
                return ResourceManager.GetString("WindowBackdropType_Mica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string WindowBackdropType_None {
            get {
                return ResourceManager.GetString("WindowBackdropType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed.
        /// </summary>
        public static string WindowBackdropType_Tabbed {
            get {
                return ResourceManager.GetString("WindowBackdropType_Tabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string WinKeyState_Off {
            get {
                return ResourceManager.GetString("WinKeyState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string WinKeyState_On {
            get {
                return ResourceManager.GetString("WinKeyState_On", resourceCulture);
            }
        }
    }
}
