//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LenovoLegionToolkit.Lib.Automation.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LenovoLegionToolkit.Lib.Automation.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 When AC power adapter is connected 的本地化字符串。
        /// </summary>
        public static string ACAdapterConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ACAdapterConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When AC power adapter is disconnected 的本地化字符串。
        /// </summary>
        public static string ACAdapterDisconnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ACAdapterDisconnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kill apps 的本地化字符串。
        /// </summary>
        public static string DeactivateGPUAutomationStepState_KillApps {
            get {
                return ResourceManager.GetString("DeactivateGPUAutomationStepState_KillApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart GPU 的本地化字符串。
        /// </summary>
        public static string DeactivateGPUAutomationStepState_RestartGPU {
            get {
                return ResourceManager.GetString("DeactivateGPUAutomationStepState_RestartGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deactivate GPU 的本地化字符串。
        /// </summary>
        public static string DeactivateGpuQuickAction_Title {
            get {
                return ResourceManager.GetString("DeactivateGpuQuickAction_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} second 的本地化字符串。
        /// </summary>
        public static string Delay_Second {
            get {
                return ResourceManager.GetString("Delay_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} seconds 的本地化字符串。
        /// </summary>
        public static string Delay_Second_Many {
            get {
                return ResourceManager.GetString("Delay_Second_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When device is connected 的本地化字符串。
        /// </summary>
        public static string DeviceConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("DeviceConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When device is disconnected 的本地化字符串。
        /// </summary>
        public static string DeviceDisconnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("DeviceDisconnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When displays turn off 的本地化字符串。
        /// </summary>
        public static string DisplayOffAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("DisplayOffAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When displays turn on 的本地化字符串。
        /// </summary>
        public static string DisplayOnAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("DisplayOnAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When external display is connected 的本地化字符串。
        /// </summary>
        public static string ExternalDisplayConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ExternalDisplayConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When external display is disconnected 的本地化字符串。
        /// </summary>
        public static string ExternalDisplayDisconnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ExternalDisplayDisconnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle 的本地化字符串。
        /// </summary>
        public static string FloatingGadgetState_Toggle {
            get {
                return ResourceManager.GetString("FloatingGadgetState_Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When game is running 的本地化字符串。
        /// </summary>
        public static string GamesAreRunningAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("GamesAreRunningAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When game closes 的本地化字符串。
        /// </summary>
        public static string GamesStopAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("GamesStopAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When Custom Mode preset changes 的本地化字符串。
        /// </summary>
        public static string GodModePresetChangedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("GodModePresetChangedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When HDR turns off 的本地化字符串。
        /// </summary>
        public static string HDROffAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("HDROffAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When HDR turns on 的本地化字符串。
        /// </summary>
        public static string HDROnAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("HDROnAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hybrid Mode 的本地化字符串。
        /// </summary>
        public static string HybridModeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("HybridModeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When IdeaPad Power Mode is changed 的本地化字符串。
        /// </summary>
        public static string ITSModeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ITSModeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lid closed 的本地化字符串。
        /// </summary>
        public static string LidClosedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LidClosedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lid opened 的本地化字符串。
        /// </summary>
        public static string LidOpenedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LidOpenedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When low wattage AC power adapter is connected 的本地化字符串。
        /// </summary>
        public static string LowWattageACAdapterConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("LowWattageACAdapterConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string MacroAutomationStepState_Off {
            get {
                return ResourceManager.GetString("MacroAutomationStepState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string MacroAutomationStepState_On {
            get {
                return ResourceManager.GetString("MacroAutomationStepState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On resume 的本地化字符串。
        /// </summary>
        public static string OnResumeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("OnResumeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On startup 的本地化字符串。
        /// </summary>
        public static string OnStartupAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("OnStartupAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Off 的本地化字符串。
        /// </summary>
        public static string OverclockDiscreteGPUAutomationStepState_Off {
            get {
                return ResourceManager.GetString("OverclockDiscreteGPUAutomationStepState_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 On 的本地化字符串。
        /// </summary>
        public static string OverclockDiscreteGPUAutomationStepState_On {
            get {
                return ResourceManager.GetString("OverclockDiscreteGPUAutomationStepState_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Periodic action 的本地化字符串。
        /// </summary>
        public static string PeriodicActionPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("PeriodicActionPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When Power Mode is changed 的本地化字符串。
        /// </summary>
        public static string PowerModeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("PowerModeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When app starts 的本地化字符串。
        /// </summary>
        public static string ProcessesAreRunningAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ProcessesAreRunningAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When app closes 的本地化字符串。
        /// </summary>
        public static string ProcessesStopRunningAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("ProcessesStopRunningAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session locked 的本地化字符串。
        /// </summary>
        public static string SessionLockAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("SessionLockAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Session unlocked 的本地化字符串。
        /// </summary>
        public static string SessionUnlockAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("SessionUnlockAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At specified time 的本地化字符串。
        /// </summary>
        public static string TimeAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("TimeAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When user becomes inactive 的本地化字符串。
        /// </summary>
        public static string UserInactivityAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("UserInactivityAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When user becomes active 的本地化字符串。
        /// </summary>
        public static string UserInactivityAutomationPipelineTrigger_DisplayName_Zero {
            get {
                return ResourceManager.GetString("UserInactivityAutomationPipelineTrigger_DisplayName_Zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When Wi-Fi is connected 的本地化字符串。
        /// </summary>
        public static string WiFiConnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("WiFiConnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When Wi-Fi is disconnected 的本地化字符串。
        /// </summary>
        public static string WiFiDisconnectedAutomationPipelineTrigger_DisplayName {
            get {
                return ResourceManager.GetString("WiFiDisconnectedAutomationPipelineTrigger_DisplayName", resourceCulture);
            }
        }
    }
}
